[package]
name = "rust-mic-test"
version = "0.1.0"
authors = ["Maor Kleinberger <kmaork@gmail.com>"]
edition = "2018"

[dependencies]
plotters = {version = "0.2.15", features = ["piston"]}
piston_window = "*" # Use the same version as plotters
cpal = "0.12.1"